get:
  tags:
    - 用户空间相关
  servers:
    - url: http://space.bilibili.com
  summary: 查询空间设置
  parameters:
    - in: query
      name: mid
      schema:
        type: integer
      required: true
      description: 目标用户 mid
  responses:
    '200':
      description: 空间设置信息
      content:
        application/json:
          schema:
            $ref: ../components/schemas/SpaceSettingsResponse.yaml
