type: object
properties:
  recFlag:
    type: integer
    description: ？
    format: int32
  recText:
    type: string
    description: ？
  recSwitch:
    type: integer
    description: ？
    format: int32
